# Site settings
title: Dainty Blog
email: 
description: "My Pet Projects"
baseurl: ""
url: "PayamBen.github.io"
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
